# Generated by Django 2.1.5 on 2019-01-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'employee'), (2, 'admin'), (3, 'super_user')], null=True),
        ),
    ]
