# Generated by Django 2.1.5 on 2019-01-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_company_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_company', to='roster.Company'),
        ),
    ]
