# Generated by Django 2.1.5 on 2019-01-21 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_auto_20190121_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='in_roster',
            new_name='using_roster',
        ),
    ]
