# Generated by Django 2.1.5 on 2019-01-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_auto_20190122_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
