# Generated by Django 2.1.5 on 2019-01-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_auto_20190123_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined_at',
        ),
    ]
