# Generated by Django 2.1.5 on 2019-01-24 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_company_joined_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Inactive', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_company', to='roster.Company')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requet_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
